#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Identity profile data helpers: phone models, file naming, and person names."""

import random
from datetime import datetime

DEVICE_DATABASE = {
    "samsung": [
        "Samsung Galaxy S24 Ultra",
        "Samsung Galaxy S24+",
        "Samsung Galaxy S24",
        "Samsung Galaxy S23 Ultra",
        "Samsung Galaxy S23+",
        "Samsung Galaxy S23",
        "Samsung Galaxy S23 FE",
        "Samsung Galaxy S22 Ultra",
        "Samsung Galaxy S22",
        "Samsung Galaxy S21 FE",
        "Samsung Galaxy A55",
        "Samsung Galaxy A54",
        "Samsung Galaxy A35",
        "Samsung Galaxy A34",
        "Samsung Galaxy A25",
        "Samsung Galaxy A15",
        "Samsung Galaxy M54",
        "Samsung Galaxy M34",
        "Samsung Galaxy Z Fold5",
        "Samsung Galaxy Z Flip5",
    ],
    "iphone": [
        "iPhone 15 Pro",
        "iPhone 15 Pro Max",
        "iPhone 15 Plus",
        "iPhone 15",
        "iPhone 14 Pro Max",
        "iPhone 14 Pro",
        "iPhone 14",
        "iPhone 13 Pro Max",
        "iPhone 13 Pro",
        "iPhone 13",
        "iPhone 12 Pro",
        "iPhone 12",
        "iPhone 11",
        "iPhone SE (3rd generation)",
    ],
    "xiaomi": [
        "Xiaomi 14 Ultra",
        "Xiaomi 14 Pro",
        "Xiaomi 14",
        "Xiaomi 13T Pro",
        "Xiaomi 13",
        "Xiaomi 12T Pro",
        "Xiaomi Redmi Note 13 Pro+",
        "Xiaomi Redmi Note 13 Pro",
        "Xiaomi Redmi Note 13",
        "Xiaomi Redmi Note 12 Pro",
        "Xiaomi Redmi 13C",
        "Xiaomi Redmi 12",
        "Xiaomi Poco F5",
        "Xiaomi Poco X6",
        "Xiaomi Poco X5 Pro",
        "Xiaomi Poco M6 Pro",
    ],
    "oppo": [
        "OPPO Find X7 Ultra",
        "OPPO Find X6 Pro",
        "OPPO Reno 11 Pro",
        "OPPO Reno 11",
        "OPPO Reno 10 Pro+",
        "OPPO Reno 10",
        "OPPO A79",
        "OPPO A78",
        "OPPO A58",
        "OPPO A38",
    ],
    "vivo": [
        "vivo X100 Pro",
        "vivo X90 Pro",
        "vivo V30",
        "vivo V29",
        "vivo V27",
        "vivo Y100",
        "vivo Y36",
        "vivo Y27",
        "vivo Y22",
    ],
    "realme": [
        "realme GT 5 Pro",
        "realme GT Neo 5",
        "realme 12 Pro+",
        "realme 12+",
        "realme 11 Pro+",
        "realme Narzo 60 Pro",
        "realme C67",
        "realme C55",
        "realme C53",
    ],
    "google": [
        "Google Pixel 8 Pro",
        "Google Pixel 8",
        "Google Pixel 8a",
        "Google Pixel 7 Pro",
        "Google Pixel 7",
        "Google Pixel 7a",
        "Google Pixel 6",
    ],
    "oneplus": [
        "OnePlus 12",
        "OnePlus 12R",
        "OnePlus 11",
        "OnePlus Nord 3",
        "OnePlus Nord CE 3",
    ],
    "asus": [
        "ASUS ROG Phone 8",
        "ASUS ROG Phone 7",
        "ASUS Zenfone 11 Ultra",
        "ASUS Zenfone 10",
    ],
    "huawei": [
        "Huawei P60 Pro",
        "Huawei Mate 50 Pro",
        "Huawei Nova 11",
        "Huawei Nova 10",
    ],
    "infinix": [
        "Infinix Zero 30",
        "Infinix Note 40 Pro",
        "Infinix Note 30",
        "Infinix Hot 40 Pro",
        "Infinix Hot 30",
    ],
    "tecno": [
        "Tecno Camon 30",
        "Tecno Camon 20 Pro",
        "Tecno Pova 6 Pro",
        "Tecno Pova 5",
        "Tecno Spark 20",
    ],
}

DEVICE_LABELS = [device for devices in DEVICE_DATABASE.values() for device in devices]

MALE_FIRST_NAMES = [
    "Ahmad",
    "Rizki",
    "Dimas",
    "Arif",
    "Fajar",
    "Budi",
    "Hendra",
    "Indra",
    "Joko",
    "Muhammad",
    "Reza",
    "Taufik",
    "Aditya",
    "Bayu",
    "Bima",
    "Fahri",
    "Farhan",
    "Ilham",
    "Iqbal",
    "Irfan",
    "Naufal",
    "Raka",
    "Ridwan",
    "Satria",
    "Surya",
    "Teguh",
    "Yusuf",
    "Zidan",
    "Abimanyu",
    "Alfin",
    "Andre",
    "Arya",
    "Bagas",
    "Dani",
    "Danu",
    "Dion",
    "Doni",
    "Ega",
    "Eka",
    "Erwin",
    "Fadli",
    "Faisal",
    "Firman",
    "Galang",
    "Gilang",
    "Guntur",
    "Hafiz",
    "Hamdan",
    "Hanif",
    "Haris",
    "Imam",
    "Ismail",
    "Jaya",
    "Kamal",
    "Kurnia",
    "Lutfi",
    "Mahendra",
    "Maulana",
    "Nanda",
    "Panji",
    "Rafli",
    "Rahmat",
    "Rangga",
    "Rizal",
    "Sandy",
    "Tegar",
    "Wahyu",
    "Yuda",
    "Zulfikar",
    "Abdullah",
    "Akmal",
    "Aldi",
    "Ammar",
    "Ardian",
    "Ariq",
    "Daffa",
    "Dzaky",
    "Fathan",
    "Fikri",
    "Ghazi",
    "Jibran",
    "Lukman",
    "Mikail",
    "Nabil",
    "Rafi",
    "Rifqi",
    "Sultan",
    "Yazid",
]

MALE_LAST_NAMES = [
    "Pratama",
    "Saputra",
    "Nugraha",
    "Setiawan",
    "Santoso",
    "Wibowo",
    "Hidayat",
    "Permana",
    "Firmansyah",
    "Maulana",
    "Hermawan",
    "Gunawan",
    "Kurniawan",
    "Nugroho",
    "Prasetyo",
    "Susanto",
    "Widodo",
    "Azhari",
    "Budiman",
    "Darmawan",
    "Hakim",
    "Ramadhan",
    "Sutopo",
    "Wicaksono",
    "Abdullah",
    "Alamsyah",
    "Anshari",
    "Ardiansyah",
    "Baskoro",
    "Budiyanto",
    "Darmono",
    "Effendi",
    "Fadillah",
    "Fajaruddin",
    "Fathurrahman",
    "Firmanto",
    "Harahap",
    "Hasibuan",
    "Iskandar",
    "Jatmiko",
    "Kusnadi",
    "Laksana",
    "Mahardika",
    "Mulyadi",
    "Nasution",
    "Nurhadi",
    "Putranto",
    "Ramdhani",
    "Riyanto",
    "Sanjaya",
    "Setyawan",
    "Siregar",
    "Subekti",
    "Sulistyo",
    "Syahputra",
    "Utomo",
    "Wahyudi",
    "Wardana",
    "Yulianto",
]

MALE_MIDDLE_NAMES = [
    "Akbar",
    "Alfian",
    "Anugrah",
    "Bagaskara",
    "Cahya",
    "Danendra",
    "Darma",
    "Fadlan",
    "Fikri",
    "Hidayat",
    "Izzuddin",
    "Januar",
    "Kurnia",
    "Maulana",
    "Nugroho",
    "Prabowo",
    "Prakoso",
    "Ramadhan",
    "Rasyid",
    "Rendra",
    "Saputra",
    "Setia",
    "Setyo",
    "Syah",
    "Wicak",
    "Wira",
    "Yudhistira",
]

FEMALE_FIRST_NAMES = [
    "Siti",
    "Dewi",
    "Ayu",
    "Nabila",
    "Putri",
    "Rina",
    "Lestari",
    "Ratna",
    "Indah",
    "Sari",
    "Fitri",
    "Wulan",
    "Maya",
    "Nurul",
    "Anisa",
    "Citra",
    "Dinda",
    "Intan",
    "Kartika",
    "Laras",
    "Mawar",
    "Nadya",
    "Raisa",
    "Safira",
    "Tiara",
    "Yasmin",
    "Zahra",
    "Syifa",
    "Adelia",
    "Afifah",
    "Aisyah",
    "Almira",
    "Amelia",
    "Aulia",
    "Azzahra",
    "Bella",
    "Bunga",
    "Cantika",
    "Clarissa",
    "Desi",
    "Dewinta",
    "Elsa",
    "Fani",
    "Farah",
    "Fitria",
    "Gita",
    "Hana",
    "Husna",
    "Ika",
    "Jihan",
    "Kirana",
    "Laila",
    "Maharani",
    "Melati",
    "Nadia",
    "Nafisa",
    "Nisa",
    "Oktavia",
    "Priska",
    "Qonita",
    "Rani",
    "Rosita",
    "Safitri",
    "Salma",
    "Shinta",
    "Tasya",
    "Ulfa",
    "Vania",
    "Windy",
    "Yuliana",
    "Aqila",
    "Aurel",
    "Azkia",
    "Dhiya",
    "Fadhila",
    "Ghania",
    "Humaira",
    "Inayah",
    "Jasmina",
    "Keisya",
    "Nayla",
    "Nazwa",
    "Qanita",
    "Rania",
    "Ratu",
    "Salsabila",
    "Shafira",
    "Zalfa",
    "Zivana",
]

FEMALE_LAST_NAMES = [
    "Lestari",
    "Permata",
    "Maharani",
    "Kartikasari",
    "Puspitasari",
    "Safitri",
    "Kusumaningrum",
    "Wulandari",
    "Anggraini",
    "Rahmawati",
    "Ningsih",
    "Febriani",
    "Azzahra",
    "Pratiwi",
    "Utami",
    "Melati",
    "Sulastri",
    "Rosdiana",
    "Handayani",
    "Susilawati",
    "Paramita",
    "Amelia",
    "Nurmala",
    "Khairunnisa",
    "Adriani",
    "Aminah",
    "Angelia",
    "Anjani",
    "Arumsari",
    "Auliawati",
    "Ayuningtyas",
    "Damayanti",
    "Dewantari",
    "Ernawati",
    "Fadilah",
    "Fitriawati",
    "Handoko",
    "Hapsari",
    "Isnaini",
    "Juwita",
    "Kuswati",
    "Lailiyah",
    "Maesaroh",
    "Mardiana",
    "Mulyani",
    "Nabilah",
    "Nuraini",
    "Octaviani",
    "Pangestuti",
    "Pertiwi",
    "Rahayu",
    "Rizqiyah",
    "Sariwati",
    "Setyaningsih",
    "Sulistyowati",
    "Trisnawati",
    "Utari",
    "Widyastuti",
    "Yuniarti",
]

FEMALE_MIDDLE_NAMES = [
    "Amalia",
    "Anindya",
    "Azzahra",
    "Cahyaning",
    "Damayanti",
    "Dewanti",
    "Febrianti",
    "Fitria",
    "Halimah",
    "Hasanah",
    "Indriyani",
    "Isnaini",
    "Khadijah",
    "Kusuma",
    "Larasati",
    "Maharani",
    "Maulida",
    "Meilani",
    "Nabilah",
    "Nadira",
    "Nurfadilah",
    "Pertiwi",
    "Rahma",
    "Rosyida",
    "Safitri",
    "Syafira",
    "Wulandari",
]


def get_random_phone_model() -> str:
    """Return a random phone model label for camera metadata generation."""
    return random.choice(DEVICE_LABELS)


def get_device_filename_pattern(device_label: str) -> list[str]:
    device_lower = device_label.lower()
    if "iphone" in device_lower:
        return ["IMG_{seq:04d}.jpg", "IMG_E{seq:04d}.jpg", "IMG_{seq:04d}.HEIC"]
    if "pixel" in device_lower:
        return ["PXL_{timestamp}.jpg", "PXL_{timestamp}.MP.jpg"]
    if "samsung" in device_lower:
        return ["20260328_{seq:06d}.jpg", "IMG_{seq:06d}.jpg"]
    return ["IMG_{seq:06d}.jpg"]


def generate_realistic_filename(device_label: str) -> str:
    patterns = get_device_filename_pattern(device_label)
    pattern = random.choice(patterns)
    return pattern.format(
        seq=random.randint(1000, 999999),
        timestamp=datetime.now().strftime("%Y%m%d_%H%M%S"),
    )


def generate_indonesian_name() -> tuple[str, str]:
    """Generate realistic 3-word Indonesian name with gender-consistent first/middle/last names."""
    gender = random.choice(["L", "P"])
    if gender == "L":
        first = random.choice(MALE_FIRST_NAMES)
        middle = random.choice(MALE_MIDDLE_NAMES)
        last = random.choice(MALE_LAST_NAMES)
    else:
        first = random.choice(FEMALE_FIRST_NAMES)
        middle = random.choice(FEMALE_MIDDLE_NAMES)
        last = random.choice(FEMALE_LAST_NAMES)
    return f"{first} {middle} {last}", gender
